#!/bin/sh
#########################################################################

SET=2016E

LIST=`echo "SingleMuReco_""$SET""_list.txt"`
#ERR=`echo "SingleMuReco_2016FGH.err"`
ERR=`echo "empty.err"`
DIROUT=$OUT/$SET/
STAT=0
PRINT=0
##########################################################################

cd $OUT
if [ ! -d $SET ]; then mkdir $SET; fi;
cd $WORK
if [ -f error_rune.txt ]; then rm error_rune.txt; fi
touch error_rune.txt

for i in `cat $LIST`; do
    DATA=$i
    echo "$DATA" >| trune
    sed "s,/, ,g" trune >| t1rune
    RESULT=`awk '{print $12}'  t1rune` 
    N=`awk '{print $12}'  t1rune`
    rm trune; rm t1rune
    if grep -q "$N" $ERR; then
       echo "File ""$DATA ""has error and excluded from analysis" >> error_rune.txt
    else

       RESULT=`echo "$DIROUT""Hist_""$RESULT"`
       echo "$RESULT" >| t3rune
       LOG=`sed "s,.root,.log,g" t3rune`
       rm t3rune
#
###  
#
       root -l -b -q ../Src/HistMan_cxx.so ../Src/AnalysisGasGain_cxx.so 'analysisgasgain.C('$STAT','$PRINT',"'$DATA'","'$RESULT'")' >| $LOG
       echo $i
    fi    
done
mv error_rune.txt error_$SET.txt
