#!/bin/sh
#########################################################################

SET=2016B

LIST=`echo "SingleMuReco_""$SET""_list.txt"`
#ERR=`echo "SingleMuReco_2016FGH.err"`
ERR=`echo "empty.err"`
DIROUT=$OUT/$SET/
STAT=0
PRINT=0
##########################################################################

cd $OUT
if [ ! -d $SET ]; then mkdir $SET; fi;
cd $WORK
if [ -f error.txt ]; then rm error.txt; fi
touch error.txt

for i in `cat $LIST`; do
    DATA=$i
    echo "$DATA" >| t
    sed "s,/, ,g" t >| t1
    RESULT=`awk '{print $12}'  t1` 
    N=`awk '{print $12}'  t1`
    rm t; rm t1
    if grep -q "$N" $ERR; then
       echo "File ""$DATA ""has error and excluded from analysis" >> error.txt
    else

       RESULT=`echo "$DIROUT""Hist_""$RESULT"`
       echo "$RESULT" >| t3
       LOG=`sed "s,.root,.log,g" t3`
       rm t3
#
###  
#
       root -l -b -q ../Src/HistMan_cxx.so ../Src/AnalysisGasGain_cxx.so 'analysisgasgain.C('$STAT','$PRINT',"'$DATA'","'$RESULT'")' >| $LOG
       echo $i
    fi    
done
mv error.txt error_$SET.txt
