#!/bin/sh
#########################################################################

SET=2016Hv2

LIST=`echo "SingleMuReco_""$SET""_list.txt"`
#ERR=`echo "SingleMuReco_2016FGH.err"`
ERR=`echo "empty.err"`
DIROUT=$OUT/$SET/
STAT=0
PRINT=0
##########################################################################

cd $OUT
if [ ! -d $SET ]; then mkdir $SET; fi;
cd $WORK
if [ -f error_runh.txt ]; then rm error_runh.txt; fi
touch error_runh.txt

for i in `cat $LIST`; do
    DATA=$i
    echo "$DATA" >| trunh
    sed "s,/, ,g" trunh >| t1runh
    RESULT=`awk '{print $12}'  t1runh` 
    N=`awk '{print $12}'  t1runh`
    rm trunh; rm t1runh
    if grep -q "$N" $ERR; then
       echo "File ""$DATA ""has error and excluded from analysis" >> error_runh.txt
    else

       RESULT=`echo "$DIROUT""Hist_""$RESULT"`
       echo "$RESULT" >| t3runh
       LOG=`sed "s,.root,.log,g" t3runh`
       rm t3runh
#
###  
#
       root -l -b -q ../Src/HistMan_cxx.so ../Src/AnalysisGasGain_cxx.so 'analysisgasgain.C('$STAT','$PRINT',"'$DATA'","'$RESULT'")' >| $LOG
       echo $i
    fi    
done
mv error_runh.txt error_$SET.txt
