#!/bin/sh
#########################################################################

SET=2016F

LIST=`echo "SingleMuReco_""$SET""_list.txt"`
#ERR=`echo "SingleMuReco_2016FGH.err"`
ERR=`echo "empty.err"`
DIROUT=$OUT/$SET/
STAT=0
PRINT=0
##########################################################################

cd $OUT
if [ ! -d $SET ]; then mkdir $SET; fi;
cd $WORK
if [ -f error_runf.txt ]; then rm error_runf.txt; fi
touch error_runf.txt

for i in `cat $LIST`; do
    DATA=$i
    echo "$DATA" >| trunf
    sed "s,/, ,g" trunf >| t1runf
    RESULT=`awk '{print $12}'  t1runf` 
    N=`awk '{print $12}'  t1runf`
    rm trunf; rm t1runf
    if grep -q "$N" $ERR; then
       echo "File ""$DATA ""has error and excluded from analysis" >> error_runf.txt
    else

       RESULT=`echo "$DIROUT""Hist_""$RESULT"`
       echo "$RESULT" >| t3runf
       LOG=`sed "s,.root,.log,g" t3runf`
       rm t3runf
#
###  
#
       root -l -b -q ../Src/HistMan_cxx.so ../Src/AnalysisGasGain_cxx.so 'analysisgasgain.C('$STAT','$PRINT',"'$DATA'","'$RESULT'")' >| $LOG
       echo $i
    fi    
done
mv error_runf.txt error_$SET.txt
