#!/bin/sh
#########################################################################

SET=2016H

LIST=`echo "SingleMuReco_""$SET""_list.txt"`
#ERR=`echo "SingleMuReco_2016FGH.err"`
ERR=`echo "empty.err"`
DIROUT=$OUT/$SET/
STAT=0
PRINT=0
##########################################################################

cd $OUT
if [ ! -d $SET ]; then mkdir $SET; fi;
cd $WORK
if [ -f error_runhv3.txt ]; then rm error_runhv3.txt; fi
touch error_runhv3.txt

for i in `cat $LIST`; do
    DATA=$i
    echo "$DATA" >| trunhv3
    sed "s,/, ,g" trunhv3 >| t1runhv3
    RESULT=`awk '{print $12}'  t1runhv3` 
    N=`awk '{print $12}'  t1runhv3`
    rm trunhv3; rm t1runhv3
    if grep -q "$N" $ERR; then
       echo "File ""$DATA ""has error and excluded from analysis" >> error_runhv3.txt
    else

       RESULT=`echo "$DIROUT""Hist_""$RESULT"`
       echo "$RESULT" >| t3runhv3
       LOG=`sed "s,.root,.log,g" t3runhv3`
       rm t3runhv3
#
###  
#
       root -l -b -q ../Src/HistMan_cxx.so ../Src/AnalysisGasGain_cxx.so 'analysisgasgain.C('$STAT','$PRINT',"'$DATA'","'$RESULT'")' >| $LOG
       echo $i
    fi    
done
mv error_runhv3.txt error_$SET.txt
