#!/bin/sh
#########################################################################

SET=2016D

LIST=`echo "SingleMuReco_""$SET""_list.txt"`
#ERR=`echo "SingleMuReco_2016FGH.err"`
ERR=`echo "empty.err"`
DIROUT=$OUT/$SET/
STAT=0
PRINT=0
##########################################################################

cd $OUT
if [ ! -d $SET ]; then mkdir $SET; fi;
cd $WORK
if [ -f error_rund.txt ]; then rm error_rund.txt; fi
touch error_rund.txt

for i in `cat $LIST`; do
    DATA=$i
    echo "$DATA" >| trund
    sed "s,/, ,g" trund >| t1rund
    RESULT=`awk '{print $12}'  t1rund` 
    N=`awk '{print $12}'  t1rund`
    rm trund; rm t1rund
    if grep -q "$N" $ERR; then
       echo "File ""$DATA ""has error and excluded from analysis" >> error_rund.txt
    else

       RESULT=`echo "$DIROUT""Hist_""$RESULT"`
       echo "$RESULT" >| t3rund
       LOG=`sed "s,.root,.log,g" t3rund`
       rm t3rund
#
###  
#
       root -l -b -q ../Src/HistMan_cxx.so ../Src/AnalysisGasGain_cxx.so 'analysisgasgain.C('$STAT','$PRINT',"'$DATA'","'$RESULT'")' >| $LOG
       echo $i
    fi    
done
mv error_rund.txt error_$SET.txt
