#!/bin/sh
#########################################################################

SET=2016C

LIST=`echo "SingleMuReco_""$SET""_list.txt"`
#ERR=`echo "SingleMuReco_2016FGH.err"`
ERR=`echo "empty.err"`
DIROUT=$OUT/$SET/
STAT=0
PRINT=0
##########################################################################

cd $OUT
if [ ! -d $SET ]; then mkdir $SET; fi;
cd $WORK
if [ -f error_runc.txt ]; then rm error_runc.txt; fi
touch error_runc.txt

for i in `cat $LIST`; do
    DATA=$i
    echo "$DATA" >| trunc
    sed "s,/, ,g" trunc >| t1runc
    RESULT=`awk '{print $12}'  t1runc` 
    N=`awk '{print $12}'  t1runc`
    rm trunc; rm t1runc
    if grep -q "$N" $ERR; then
       echo "File ""$DATA ""has error and excluded from analysis" >> error_runc.txt
    else

       RESULT=`echo "$DIROUT""Hist_""$RESULT"`
       echo "$RESULT" >| t3runc
       LOG=`sed "s,.root,.log,g" t3runc`
       rm t3runc
#
###  
#
       root -l -b -q ../Src/HistMan_cxx.so ../Src/AnalysisGasGain_cxx.so 'analysisgasgain.C('$STAT','$PRINT',"'$DATA'","'$RESULT'")' >| $LOG
       echo $i
    fi    
done
mv error_runc.txt error_$SET.txt
